PREFIX sr:<http://www.semanticweb.org/matteo/ontologies/2016/11/OperazioneStudyRoom#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
INSERT DATA {
	sr:IT_BO_AlmaMater	rdf:type sr:University;
						rdfs:label "Alma Mater Studiorum - Universita' di Bologna".
	sr:IT_BO_AlmaMater_ing_1	rdf:type sr:StudyRoom;
								sr:hasName "Aula studio lab.4 ingegneria";
								sr:inUniversity sr:IT_BO_AlmaMater;
								sr:hasStudyRoomFeature sr:accessibleToilet
								sr:hasStudyRoomFeature sr:accessibleToilet
								sr:hasStudyRoomFeature sr:accessibleToilet
								sr:hasStudyRoomFeature sr:accessibleToilet
}